name: download regional CMEMS waves data

on:
  workflow_call:
    inputs:
      MODEL_TYPE:
        description: 'type of model being run'
        required: true
        type: string
      RUNNER_NAME:
        description: 'specify the runner name to determine what server we are running on'
        required: true
        type: string
      RUN_DATE:
        description: 'time of T0 of the model run - defined dynamically in run_ops.yml'
        required: true
        type: string
      BRANCH_REF:
        description: 'what branch are we on - defined dynamically in run_ops.yml'
        required: true
        type: string
      HDAYS:
        description: 'number of hindcast days (integer) from T0'
        required: true
        type: string
      FDAYS:
        description: 'number of forecast days (integer) from T0'
        required: true
        type: string

env:
  DATA_DIR: /home/somisana/ops/${{ inputs.BRANCH_REF }}/${{ inputs.RUN_DATE }}/downloaded_data

jobs:
  check_files:
    # checks to see if files have maybe already been downloaded as part of a previous running of this workflow
    runs-on: ${{ inputs.RUNNER_NAME }}
    outputs:
      WAVES_OK: ${{ steps.check_waves.outputs.value }}
    steps:
      - name: Check if WAVES file is already downloaded
        id: check_waves
        run: |
          FILE_PATH=${{ env.DATA_DIR }}/CMEMS/CMEMS_${{ inputs.RUN_DATE }}.nc
          # could have an additional check on file size here?
          if [ -f "$FILE_PATH" ]; then
            echo "value=1" >> $GITHUB_OUTPUT
          else
            echo "value=0" >> $GITHUB_OUTPUT
          fi

  download_cmems_waves_saeon:
    # we have had an issue with downloading from copernicus specifically on the mims network
    # it seems this is something idiosyncratic to the mims network and the copernicusmarine cli at the time of testing
    # so for now we are just downloading on the saeon-apps server, and moving to the shared
    # samba mount which is accessible on from both the saeon and mimms servers
    # we can come back to this when we have the server issue sorted (or if later versions of 
    # the copernicusmarine tool works better on this network)
    # then this job can be deleted and the commented download step in the mercator job can be used
    runs-on: saeonapps
    needs: [check_files]
    if: ${{ needs.check_files.outputs.WAVES_OK == '0' }}
    steps:
      - name: Skip unless phytodrift
        if: ${{ inputs.MODEL_TYPE != 'phytodrift' }}
        run: |
          echo "Not phytodrift. Nothing to do."
          exit 0
      - name: pull latest download docker image to the saeon-apps server
        run: |
          docker pull ghcr.io/saeon/somisana-download_main:latest
      - name: Format RUN_DATE
        id: format_date
        run: |
          run_date=${{ inputs.RUN_DATE }}
          run_date_formatted="'${run_date:0:4}-${run_date:4:2}-${run_date:6:2} ${run_date:9:2}:00:00'"
          echo "value=$run_date_formatted" >> $GITHUB_OUTPUT
      - name: clean up files on saeonapps
        run: |
          # this is a terrible hack I know...
          # The cli wouldn't run as a non-root user due to permissions issues on saeonapps (even though I did try to get around this in visudo)
          # so the output from the cli in owned by root, making it hard to clean up as a non-root user operationally
          # so I'm using the cli docker image to remove the files it originally created
          download_dir=/home/giles/mercator_download
          docker run \
            --rm \
            --entrypoint /bin/bash \
            -v ${download_dir}:/mnt/tmp \
            ghcr.io/saeon/somisana-download_main:latest \
              -c "rm -f /mnt/tmp/*nc"
      - name: download CMEMS
        run: |
          download_dir=/home/giles/mercator_download
          mkdir -p ${download_dir}
          docker run \
            --rm \
            -v ${download_dir}:/tmp/download \
            ghcr.io/saeon/somisana-download_main:latest \
            download_cmems_ops \
              --usrname grautenbach \
              --passwd ZuluTheMoo2021! \
              --dataset cmems_mod_glo_wav_anfc_0.083deg_PT3H-i \
              --varList "VHM0,VTPK,VMDR" \
              --domain 11,36,-39,-25 \
              --depths 0,0 \
              --run_date ${{ steps.format_date.outputs.value }} \
              --hdays ${{ inputs.HDAYS }} \
              --fdays ${{ inputs.FDAYS }} \
              --outputDir "/tmp/download" \
              --outputFile "CMEMS_${{ inputs.RUN_DATE }}.nc"

          # copy to a shared dir
          sudo cp ${download_dir}/CMEMS_${{ inputs.RUN_DATE }}.nc /mnt/somisana/data/shared/CMEMS_${{ inputs.RUN_DATE }}.nc

  download_cmems_waves:
    runs-on: ${{ inputs.RUNNER_NAME }}
    needs: [check_files,download_cmems_waves_saeon]
    if: ${{ inputs.MODEL_TYPE == 'phytodrift' && needs.check_files.outputs.WAVES_OK == '0' }}
    steps:
      - name: create the CMEMS directory
        run: |
          if [ ! -d "${{ env.DATA_DIR }}/CMEMS" ]; then
            mkdir -p ${{ env.DATA_DIR }}/CMEMS
            chown -R :runners ${{ env.DATA_DIR }}/CMEMS
            chmod -R 774 ${{ env.DATA_DIR }}/CMEMS
          fi
      - name: move downloaded file from the shared mount
        # we only need this since we have the workaround of downloading on saeonapps
        # so this essentially replaces the commented download code below
        run: |
          set -e
          file="/mnt/saeon-somisana/data/shared/CMEMS_${{ inputs.RUN_DATE }}.nc"
          dest="${{ env.DATA_DIR }}/CMEMS/CMEMS_${{ inputs.RUN_DATE }}.nc"
          sudo cp "$file" "$dest"

  archive_ocims:
    # copy the data to an archive directory on ocims infrastructure, mounted to the mims compute server
    needs: [download_cmems_waves]
    runs-on: ${{ inputs.RUNNER_NAME }}
    # only archive if we are on the main branch
    if: ${{ always() && inputs.BRANCH_REF == 'main' }}
    continue-on-error: true
    steps:
      - name: archive forcing files on ocims infrastructure
        id: archive_dir
        run: |
          # get the archive directory name
          run_date=${{ inputs.RUN_DATE }}
          run_date_yyyymm=${run_date:0:6}
          run_date_hh=${run_date:9:2}
          archive_dir=/mnt/somisana_safe/models/sa-forcing/${run_date_yyyymm}/${run_date}
          # also copying it to the public facing directory, just in case we might need it
          archive_dir_public=/mnt/ocims-somisana/public-facing/sa-forcing/${run_date}
          # make the archive directory
          sudo mkdir -p ${archive_dir}/CMEMS
          sudo mkdir -p ${archive_dir_public}/CMEMS
          # only archive one run per day (initialised at 00)
          # the archiving is really for validation purposes, and I think one run per day is sufficient for this
          if [ "${run_date_hh}" == "00" ]; then 
            # We need to use sudo in the lines below because the target dir is owned by root
            # Not an issue since we have ensured no password is needed for this command 
            sudo cp ${{ env.DATA_DIR }}/CMEMS/CMEMS_${{ inputs.RUN_DATE }}.nc ${archive_dir}/CMEMS/
            sudo cp ${{ env.DATA_DIR }}/CMEMS/CMEMS_${{ inputs.RUN_DATE }}.nc ${archive_dir_public}/CMEMS/
          fi
