name: run the model

on:
  workflow_call:
    inputs:
      MODEL_TYPE:
        description: 'what kind of model are we running e.g. oil - a user defined input in run_ops.yml'
        required: true
        type: string
      BRANCH_REF:
        description: 'what branch are we on - defined dynamically in run_ops.yml'
        required: true
        type: string
      CONFIG_NAME:
        description: 'configuration name - defined dynamically in run_ops.yml'
        required: true
        type: string
      RUN_DATE:
        description: 'time of T0 of the croco workflow in format YYYYMMDD_HH - defined dynamically in run_ops.yml'
        required: true
        type: string
      RUNNER_NAME:
        description: 'specify the runner name to determine what server we are running on'
        required: true
        type: string
      WIND:
        description: 'name of wind forcing e.g. GFS' 
        required: true
        type: string
      OGCM:
        description: 'name of boundary forcing e.g. MERCATOR' 
        required: true
        type: string

env:
  RUN_DIR: /home/somisana/ops/${{ inputs.BRANCH_REF }}/${{ inputs.RUN_DATE }}/opendrift_${{ inputs.MODEL_TYPE }}/${{ inputs.CONFIG_NAME }}/${{ inputs.OGCM }}_${{ inputs.WIND }}
  DATE_DIR: /home/somisana/ops/${{ inputs.BRANCH_REF }}/${{ inputs.RUN_DATE }}

jobs:
  setup-run-dir:
    runs-on: ${{ inputs.RUNNER_NAME }}
    steps:
      - name: Check out source code so have access to the files in the repo
        uses: actions/checkout@main
        with:
          ref: ${{ inputs.BRANCH_REF }}

      - name: create the directory
        run: |
          rm -rf ${{ env.RUN_DIR }}  
          mkdir -p ${{ env.RUN_DIR }}

      - name: Copy config file to the local server to run the model
        run: |
          OGCM=${{ inputs.OGCM }}
          WIND=${{ inputs.WIND }} 
          sed -e 's/OGCM/'$OGCM'/g' -e 's/WIND/'$WIND'/g' < configs/config_${{ github.event.inputs.model_type }}.py > ${{ env.RUN_DIR }}/config.py

      - name: add permissions to the config file
        run: |
          chmod -R 774 ${{ env.RUN_DIR }}
        continue-on-error: true

  run-model:
    needs: [setup-run-dir]
    runs-on: ${{ inputs.RUNNER_NAME }}
    steps:
      - name: run the model
        run: |
          # we're specifying --user root due to permission issues I wasn't clever enough to solve
          docker run \
            --rm \
            --user root \
            -v ${{ env.DATE_DIR }}:/mnt/tmp \
            ghcr.io/saeon/somisana-opendrift_${{ inputs.BRANCH_REF }}:latest \
              run_${{ inputs.MODEL_TYPE }}  \
                --config_dir /mnt/tmp/opendrift_${{ inputs.MODEL_TYPE }}/${{ inputs.CONFIG_NAME }}/${{ inputs.OGCM }}_${{ inputs.WIND }}

          # specifying --user root means the outputs have root permissions so hard to delete them, hence this hack 
          docker run \
            --rm \
            --user root \
            --entrypoint /bin/bash \
            -v ${{ env.DATE_DIR }}:/mnt/tmp \
            ghcr.io/saeon/somisana-opendrift_${{ inputs.BRANCH_REF }}:latest \
              -c "chown -R $(id -u):$(id -g) /mnt/tmp/opendrift_${{ inputs.MODEL_TYPE }}/${{ inputs.CONFIG_NAME }}/${{ inputs.OGCM }}_${{ inputs.WIND }}"
