name: Sandbox for testing individual calleable workflows

on:
  workflow_dispatch:
    inputs:
      model_type:
        description: "The kind of model to run"
        required: true
        default: oceandrift
        type: choice
        options: [oceandrift, oil, leeway, phytodrift]

      run_model:
        description: "run the model?"
        required: true
        type: boolean
        default: true

      do_post:
        description: "do the postprocessing?"
        required: true
        type: boolean
        default: true

      extents:
        description: "lon0,lon1,lat0,lat1 or None"
        required: true
        default: None
        type: string

      dx_m:
        description: "grid size (m) or None"
        required: true
        default: None
        type: string

###############################################################################
# Detect branch
###############################################################################

jobs:
  branch-ref:
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.branch.outputs.value }}

    steps:
      - id: branch
        run: echo "value=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

###############################################################################
# Load derived config (single source of truth)
###############################################################################

  envs:
    needs: branch-ref
    runs-on: ubuntu-latest

    outputs:
      BRANCH_REF: ${{ needs.branch-ref.outputs.value }}
      CONFIG_NAME: ${{ steps.config.outputs.value }}
      RUN_DATE: ${{ steps.rundate.outputs.value }}
      MODEL_TYPE: ${{ github.event.inputs.model_type }}
      RUN_MODEL: ${{ github.event.inputs.run_model }}
      DO_POST: ${{ github.event.inputs.do_post }}
      EXTENTS: ${{ github.event.inputs.extents }}
      DX_M: ${{ github.event.inputs.dx_m }}

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.branch-ref.outputs.value }}

      - name: Read config_name
        id: config
        run: |
          line=$(grep -m 1 -w config_name configs/config_${{ github.event.inputs.model_type }}.py)
          value=$(echo "$line" | awk -F "=" '{print $2}' | sed 's/^[[:space:]]*//' | sed "s/^['\"]//;s/['\"]$//")
          echo "value=$value" >> $GITHUB_OUTPUT

      - name: Read run_date
        id: rundate
        run: |
          line=$(grep -m 1 -w run_date configs/config_${{ github.event.inputs.model_type }}.py)
          value=$(echo "$line" | awk -F "=" '{print $2}' | sed "s/^[[:space:]]*//" | sed "s/^['\"]//;s/['\"]$//")
          echo "value=$value" >> $GITHUB_OUTPUT


###############################################################################
# Build image
###############################################################################

  build_image:
    uses: ./.github/workflows/build_image.yml


###############################################################################
# Download phytoplankton flags
###############################################################################
  
  download_phytoplankton_flags: 
    if: ${{ github.event.inputs.model_type == 'phytodrift' }}
    needs: [build_image,envs]
    uses: ./.github/workflows/download_phytoplankton_flags.yml
    with:
      RUNNER_NAME: mims3
      RUN_DATE: ${{ needs.envs.outputs.RUN_DATE }}
      BRANCH_REF: ${{ needs.envs.outputs.BRANCH_REF }}
    secrets: inherit


###############################################################################
# Download CMEMS waves
###############################################################################

  download_cmems_waves:
    if: ${{ github.event.inputs.model_type == 'phytodrift' }}
    needs: [build_image,envs]
    uses: ./.github/workflows/download_cmems_waves.yml
    with:
      RUNNER_NAME: mims3
      RUN_DATE: ${{ needs.envs.outputs.RUN_DATE }}
      BRANCH_REF: ${{ needs.envs.outputs.BRANCH_REF }}
      HDAYS: 5
      FDAYS: 5
    secrets: inherit

###############################################################################
# Check available models
###############################################################################

  check_models:
    runs-on: mims3
    outputs:
      RUN_GFS_MERCATOR: ${{ steps.check.outputs.RUN_GFS_MERCATOR }}
      RUN_SAWS_MERCATOR: ${{ steps.check.outputs.RUN_SAWS_MERCATOR }}
      RUN_GFS_HYCOM: ${{ steps.check.outputs.RUN_GFS_HYCOM }}
      RUN_SAWS_HYCOM: ${{ steps.check.outputs.RUN_SAWS_HYCOM }}

    steps:
      - id: check
        run: |
          BASE=/mnt/ocims-somisana/public-facing/sa-west/v1.0/forecasts/latest

          [ -d "$BASE/MERCATOR-GFS" ] && echo "RUN_GFS_MERCATOR=true" >> $GITHUB_OUTPUT || echo "RUN_GFS_MERCATOR=false" >> $GITHUB_OUTPUT
          [ -d "$BASE/MERCATOR-SAWS" ] && echo "RUN_SAWS_MERCATOR=true" >> $GITHUB_OUTPUT || echo "RUN_SAWS_MERCATOR=false" >> $GITHUB_OUTPUT
          [ -d "$BASE/HYCOM-GFS" ] && echo "RUN_GFS_HYCOM=true" >> $GITHUB_OUTPUT || echo "RUN_GFS_HYCOM=false" >> $GITHUB_OUTPUT
          [ -d "$BASE/HYCOM-SAWS" ] && echo "RUN_SAWS_HYCOM=true" >> $GITHUB_OUTPUT || echo "RUN_SAWS_HYCOM=false" >> $GITHUB_OUTPUT


# ###############################################################################
# # RUN MODELS
# ###############################################################################

  run_GFS_MERCATOR:
    needs: [envs, check_models, build_image,download_phytoplankton_flags,download_cmems_waves]
    if: needs.check_models.outputs.RUN_GFS_MERCATOR == 'true'
    uses: ./.github/workflows/run_model.yml
    with:
      MODEL_TYPE: ${{ needs.envs.outputs.MODEL_TYPE }}
      BRANCH_REF: ${{ needs.envs.outputs.BRANCH_REF }}
      CONFIG_NAME: ${{ needs.envs.outputs.CONFIG_NAME }}
      RUN_DATE: ${{ needs.envs.outputs.RUN_DATE }}
      RUNNER_NAME: mims3
      WIND: GFS
      OGCM: MERCATOR
      WAVES: CMEMS
      RUN_MODEL: ${{ needs.envs.outputs.RUN_MODEL }}
      DO_POST: ${{ needs.envs.outputs.DO_POST }}
      EXTENTS: ${{ needs.envs.outputs.EXTENTS }}
      DX_M: ${{ needs.envs.outputs.DX_M }}


  run_SAWS_MERCATOR:
    needs: [envs, check_models, build_image,download_phytoplankton_flags,download_cmems_waves]
    if: needs.check_models.outputs.RUN_SAWS_MERCATOR == 'true'
    uses: ./.github/workflows/run_model.yml
    with:
      MODEL_TYPE: ${{ needs.envs.outputs.MODEL_TYPE }}
      BRANCH_REF: ${{ needs.envs.outputs.BRANCH_REF }}
      CONFIG_NAME: ${{ needs.envs.outputs.CONFIG_NAME }}
      RUN_DATE: ${{ needs.envs.outputs.RUN_DATE }}
      RUNNER_NAME: mims3
      WIND: SAWS
      OGCM: MERCATOR
      WAVES: CMEMS
      RUN_MODEL: ${{ needs.envs.outputs.RUN_MODEL }}
      DO_POST: ${{ needs.envs.outputs.DO_POST }}
      EXTENTS: ${{ needs.envs.outputs.EXTENTS }}
      DX_M: ${{ needs.envs.outputs.DX_M }}


  run_GFS_HYCOM:
    needs: [envs, check_models, build_image,download_phytoplankton_flags,download_cmems_waves]
    if: needs.check_models.outputs.RUN_GFS_HYCOM == 'true'
    uses: ./.github/workflows/run_model.yml
    with:
      MODEL_TYPE: ${{ needs.envs.outputs.MODEL_TYPE }}
      BRANCH_REF: ${{ needs.envs.outputs.BRANCH_REF }}
      CONFIG_NAME: ${{ needs.envs.outputs.CONFIG_NAME }}
      RUN_DATE: ${{ needs.envs.outputs.RUN_DATE }}
      RUNNER_NAME: mims3
      WIND: GFS
      OGCM: HYCOM
      WAVES: CMEMS
      RUN_MODEL: ${{ needs.envs.outputs.RUN_MODEL }}
      DO_POST: ${{ needs.envs.outputs.DO_POST }}
      EXTENTS: ${{ needs.envs.outputs.EXTENTS }}
      DX_M: ${{ needs.envs.outputs.DX_M }}


  run_SAWS_HYCOM:
    needs: [envs, check_models, build_image,download_phytoplankton_flags,download_cmems_waves]
    if: needs.check_models.outputs.RUN_SAWS_HYCOM == 'true'
    uses: ./.github/workflows/run_model.yml
    with:
      MODEL_TYPE: ${{ needs.envs.outputs.MODEL_TYPE }}
      BRANCH_REF: ${{ needs.envs.outputs.BRANCH_REF }}
      CONFIG_NAME: ${{ needs.envs.outputs.CONFIG_NAME }}
      RUN_DATE: ${{ needs.envs.outputs.RUN_DATE }}
      RUNNER_NAME: mims3
      WIND: SAWS
      OGCM: HYCOM
      WAVES: CMEMS
      RUN_MODEL: ${{ needs.envs.outputs.RUN_MODEL }}
      DO_POST: ${{ needs.envs.outputs.DO_POST }}
      EXTENTS: ${{ needs.envs.outputs.EXTENTS }}
      DX_M: ${{ needs.envs.outputs.DX_M }}

###############################################################################
# Combine output
###############################################################################

  # combine_output:
  #   needs: [envs, run_GFS_MERCATOR, run_SAWS_MERCATOR, run_GFS_HYCOM, run_SAWS_HYCOM]
  #   if: ${{ always() && needs.envs.outputs.DO_POST == 'true' }}

  #   uses: ./.github/workflows/combine_output.yml
  #   with:
  #     MODEL_TYPE: ${{ needs.envs.outputs.MODEL_TYPE }}
  #     BRANCH_REF: ${{ needs.envs.outputs.BRANCH_REF }}
  #     CONFIG_NAME: ${{ needs.envs.outputs.CONFIG_NAME }}
  #     RUN_DATE: ${{ needs.envs.outputs.RUN_DATE }}
  #     RUNNER_NAME: mims3
  #     EXTENTS: ${{ needs.envs.outputs.EXTENTS }}
  #     DX_M: ${{ needs.envs.outputs.DX_M }}

